### ISSUE TITLE
possible to customize join table names?

### ISSUE THREAD

**Issue by tjwebb** [balderdashy/waterline-schema#15]
https://github.com/balderdashy/waterline-schema/blob/master/lib/waterline-schema/joinTables.js#L229-L240

Is it possible to specify my own join table names without stomping on this function?

**Comment by devinivy** [comment]
Sounds like the answer is that we cannot use custom join tables.  For the time being, use the limited, undocumented support of through associations.  I've requested this option as an enhancement in #20.

@tjwebb I realize that this project doesn't have a ROADMAP.md and that this feature doesn't fit into the waterline core roadmap.  Do you mind making a ROADMAP.md file for this repo and adding the feature?  I would do it myself, but I'm not sure exactly how balderdashy likes to organize this sorts of things!
