### ISSUE TITLE
Test for special attribute names - aka "type"

### ISSUE THREAD

**Issue by particlebanana** [balderdashy/waterline-schema#22]
Moving from https://github.com/balderdashy/waterline/pull/789 to here as I suspect it has to do with normalizing the schema. We need to test it.

cc @bradshja

**Comment by dmarcelino** [comment]
This also continues the discussion of balderdashy/waterline#788, the issue that lead to PR balderdashy/waterline#789.

cc @bradshja, @dasher, @atiertant

**Comment by devinivy** [comment]
At first glance, I don't see anything that would treat `type` specially when used as an attribute name inside this repo.

**Comment by devinivy** [comment]
I think that @bradshja was exactly right in https://github.com/balderdashy/waterline/issues/788.  Check out `waterlineInstance.schema._schema` after passing through the transformer [here](https://github.com/balderdashy/waterline/blob/master/lib/waterline/core/index.js#L103-L104).

Model:
```
    user: {
      connection: 'tmp',
      attributes: {
        'type': {
          type: 'string',
          columnName: 'NOTTEST'
        }
      }
    }
```

`waterlineInstance.schema._schema` after transformation:
```
 { id: 
   { autoIncrement: true,
     primaryKey: true,
     unique: true,
     NOTTEST: 'integer' },
  createdAt: { NOTTEST: 'datetime' },
  updatedAt: { NOTTEST: 'datetime' },
  NOTTEST: { NOTTEST: 'string' } }
```

Perhaps we should close this and bounce back to the waterline issue.

**Comment by dmarcelino** [comment]
Indeed, the transformer seems to be where the issue lies. @particlebanana, shall we close this one and reopen balderdashy/waterline#788 and PR balderdashy/waterline#789?

**Comment by devinivy** [comment]
I'm not entirely convinced that https://github.com/balderdashy/waterline/pull/789 is the solution to the problem, but I do think we should carry-on the conversation over at https://github.com/balderdashy/waterline/pull/789.

**Comment by atiertant** [comment]
the problem is that the transformer is recursive and transform every keys based only on the name.
to do it correctly,transformer should care about what kind of key he is transforming : 
is it an attribute name or a waterline syntax key,... ?
maybe using the parent type a good way.

**Comment by devinivy** [comment]
Yes, it seems like the transformer is used in exactly three ways: on schema, on criteria, and on values.  Perhaps when the transformer is acting, it should know which of the three it's working on, and adjust its behavior accordingly.  I understand why https://github.com/balderdashy/waterline/pull/789 works, but maybe it's worth investigating a more explicit, descriptive solution.

**Comment by atiertant** [comment]
well, do you think transformer should be call like this => serialize(attributes,behavior) 

    this._schema.schema = this._transformer.serialize(this._schema.schema, 'schema');

so in function we test if behavior is 'schema' before recurse, or

    this._schema.schema = this._transformer.schemaSerialize(this._schema.schema);

that would be a separate function simpler than serialize.which one one could be more explicit ?

**Comment by devinivy** [comment]
I think either is reasonable.  Another option is to curry these functions and require that the serializer with the correct behavior be explicitly obtained.
```
var Serializer = this._transformer.serialize('schema');
this._schema.schema = Serializer(this._schema.schema);
```

**Comment by atiertant** [comment]
i like you solution,it's elegant but it break serialize function compatibility so need more modifications...
in this point of view, i think first one is the best,do you agree ?

**Comment by devinivy** [comment]
Sure– I would be fine with that.  Thanks for all the help, @atiertant.

**Comment by atiertant** [comment]
@devinivy: fix: https://github.com/balderdashy/waterline/pull/995

**Comment by particlebanana** [comment]
Fixed by https://github.com/balderdashy/waterline/pull/995
