### ISSUE TITLE
Prepare and release 0.1.18

### ISSUE THREAD

**Issue by dmarcelino** [balderdashy/waterline-schema#25]
@particlebanana, @tjwebb, I believe we've reached a good moment to release waterline-schema v0.1.18. There are currently [13 commits](https://github.com/balderdashy/waterline-schema/compare/0.1.17...master) since v0.1.17 (Dec 3, 2014) waiting in master to be released and 2 PRs that should be seriously considered.

Tasks:
- [ ] Review (and merge) PR #23
- [x] Review (and merge) PR #24
- [x] Bump package.json version to 0.1.18
- [x] Release to npm

cc: @devinivy

**Comment by particlebanana** [comment]
@dmarcelino I'm going to go ahead and publish `0.1.18` as is. I'll merge #23 after looking it over and then we will need to go to `0.2.0` when that's published.

**Comment by dmarcelino** [comment]
Fair enough.

**Comment by particlebanana** [comment]
published `0.2.0-rc1` and created a branch for further `0.1.x` patches.

**Comment by dmarcelino** [comment]
sweet :+1:
