### ISSUE TITLE
Deactivate join tables

### ISSUE THREAD

**Issue by smith64fx** [balderdashy/waterline-schema#29]
Hey there,
We are developing an adapter for a graph database. Tough we don't need join tables, is there any configuration, how to tell waterline-schema not to use join tables?

Regards,
Michael

**Comment by devinivy** [comment]
There's no such configuration.  waterline-schema uses relational terms to talk about associations, but your implementation details do not have to follow suit.  That is, you do not need to create an actual table to represent a what the schema would call a junction table.  @dmarcelino has some experience with this working on [sails-orientdb](https://github.com/appscot/sails-orientdb), and that might be a good codebase to look at.
