### ISSUE TITLE
How to create an actual DB relation?

### ISSUE THREAD

**Issue by Sogl** [balderdashy/waterline-schema#35]
Hi!

I'm trying to use waterline to create my DB schema. Now I have 2 models: `user` and `example`. I want to create relation between them with FK. 
Part from `example.js`:
```javascript
user: {
      columnName: 'userId',
      type: 'integer',
      foreignKey: true,
      references: 'user',
      on: 'id'
    }
```

Result:
![3](https://cloud.githubusercontent.com/assets/7556290/12816744/7b53a6d2-cb91-11e5-9150-5144b8303dd3.png)

It creates `userId` fine but I want it with DB realation, like this:
![4](https://cloud.githubusercontent.com/assets/7556290/12816980/da95c282-cb92-11e5-905a-b0f87bc4bb84.png)

How to do it with waterline?

**Comment by Sogl** [comment]
@particlebanana @dmarcelino Anybody here?

**Comment by devinivy** [comment]
You will want to define a "collection" on one end, and a "model" on the other end to define the complete one-to-many relationship.  The FK should naturally reference the primary key of the foreign model.  For more info see https://github.com/balderdashy/waterline-docs/blob/master/models/associations/associations.md.
```json5
// example.js
user: {
  columnName: 'userId',
  model: 'user'
}
```
```json5
// user.js
examples: {
  collection: 'example',
  via: 'user' // name of FK attribute
}
```

**Comment by Sogl** [comment]
@devinivy Waterline can use model relations without DB relation? In DB relation I mean difference beetwen 2 my screenshots in [first message](https://github.com/balderdashy/waterline-schema/issues/35#issue-131356118).

I need one-to-one association in my case. 1 person has one user (`user.js` is built-in model, I can't change or extend it for now).

So.. what I missed to create DB relation?

**Comment by particlebanana** [comment]
@Sogl you can create the foreign key constraints using database migrations to create and modify the tables. Take a look into [Sails-Migrations](https://github.com/BlueHotDog/sails-migrations) for one example.
